### PR TITLE
switch to template strings

### PR DESCRIPTION
**Pull request by Haroenv**
no more need for handlebars too

closes #4

### CODE REVIEW

**Comment by dervondenbergen** [comment]
👍

**Comment by Haroenv** [comment]
can I merge this @dervondenbergen, do you know where to re-deploy it? We also need to change the config.js on the server

**Comment by dervondenbergen** [comment]
I still have Node.js v0.12.0 running on the uberspace ➡️ I have to check which applications will break when updating Node to a version which supports template literals.

**Comment by Haroenv** [comment]
did we update since @dervondenbergen ?

**Comment by dervondenbergen** [comment]
Oh shit, no. Still running on an old version. 😢

**Comment by dervondenbergen** [comment]
fixed with fe4af9ff18851442c16455d4bd7eb65d3b690326

**Pull request closed without merging**
